language: c
sudo: required
dist: trusty # modern Python

before_install:
  - sudo apt-get update
  - >
    sudo apt-get install --yes
    g++ cmake make libqt4-dev libboost-dev libyaml-cpp-dev python3-yaml
  - sudo pip install cpp-coveralls

install:
  - cmake .
  - make

before_script:
  - sudo apt-get install --yes valgrind

script:
  - valgrind ./unit_test
  - coveralls --include src

after_success:
  - cd ./integration_tests
  - ./run_tests.sh ../integration_test
