language: c
sudo: required
dist: trusty # modern Python

before_install:
  - sudo apt-get update
  - >
    sudo apt-get install --yes
    g++ cmake make libqt4-dev libboost-dev libyaml-cpp-dev
  - sudo pip install cpp-coveralls pyyaml

install:
  - cmake .
  - make

before_script:
  - sudo apt-get install --yes valgrind

script:
  - valgrind ./bacteria_test
  - ./integration_tests/run_tests.sh ./integration_test

after_success:
  - coveralls --include src
