#!/usr/bin/env python

""" Check results of execution of integration tests.

Compare .yaml files:
 - Generated by integration tests
 - Canonized correct results (reference data)
"""

import argparse
import yaml

def compare(expected_filename, observed_filename):
    with open(expected_filename) as expected_file:
        expected = yaml.load(expected_file)
    with open(observed_filename) as observed_file:
        observed = yaml.load(observed_file)
    assert expected == observed

def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        '--expected',
        type=str,
        help='Yaml file with expected results',
        required=True,
    )
    parser.add_argument(
        '--observed',
        type=str,
        help='Yaml file with observed results',
        required=True,
    )
    args = parser.parse_args()
    compare(args.expected, args.observed)

if __name__ == '__main__':
    main()
